// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw8uMWpKXJ4sqWBXN4K0XDozq3Iyj1Yho',
    appId: '1:745453900534:android:198083a6e88edeaa1112d7',
    messagingSenderId: '745453900534',
    projectId: 'finsecfam',
    storageBucket: 'finsecfam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9IschExmGjBx4QtIVNVAdIL2YP4gKBI',
    appId: '1:745453900534:ios:c1a972c1800d51101112d7',
    messagingSenderId: '745453900534',
    projectId: 'finsecfam',
    storageBucket: 'finsecfam.appspot.com',
    androidClientId: '745453900534-vu547h1sql7tc10d5b09mpti3a9c3f9k.apps.googleusercontent.com',
    iosClientId: '745453900534-5341ortks7crqakseocr95rq3hg48vlq.apps.googleusercontent.com',
    iosBundleId: 'in.innovativeminds.finsec',
  );

}